spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/archipellibre
    username: ${DB_USERNAME:archipellibre}
    password: ${DB_PASSWORD:changeme}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    com.archipellibre: DEBUG
